# Generated by Django 2.1.7 on 2019-05-07 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_Organization', models.CharField(max_length=50)),
                ('Address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Visaletters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_passenger', models.IntegerField(default=1)),
                ('Country', models.CharField(choices=[('INDIA', 'India'), ('USA', 'Usa'), ('UK', 'Uk'), ('CHINA', 'China'), ('JAPAN', 'Japan')], default='INDIA', max_length=264)),
                ('entry_from', models.CharField(max_length=200)),
                ('departure_to', models.CharField(max_length=200)),
                ('Visa_Letter_Number', models.CharField(default='1', max_length=264)),
                ('Date_of_letter', models.CharField(blank=True, max_length=200)),
                ('Routes_and_Places', models.CharField(default='MOSCOW', max_length=500)),
                ('hotels', models.CharField(max_length=264)),
                ('Organization', models.CharField(blank=True, max_length=200)),
                ('Payment_status', models.CharField(choices=[('Paid', 'Paid'), ('unpaid', 'unpaid')], default='unpaid', max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('firstname_1', models.CharField(max_length=264)),
                ('lastname_1', models.CharField(max_length=264)),
                ('Passport_Number_1', models.CharField(max_length=200, unique=True)),
                ('Date_Of_Birth_1', models.CharField(max_length=200)),
                ('Sex_1', models.CharField(max_length=100)),
                ('firstname_2', models.CharField(blank=True, max_length=264)),
                ('lastname_2', models.CharField(blank=True, max_length=264)),
                ('Passport_Number_2', models.CharField(blank=True, max_length=200)),
                ('Date_Of_Birth_2', models.CharField(blank=True, max_length=200)),
                ('Sex_2', models.CharField(blank=True, max_length=100)),
                ('firstname_3', models.CharField(blank=True, max_length=264)),
                ('lastname_3', models.CharField(blank=True, max_length=264)),
                ('Passport_Number_3', models.CharField(blank=True, max_length=200)),
                ('Date_Of_Birth_3', models.CharField(blank=True, max_length=200)),
                ('Sex_3', models.CharField(blank=True, max_length=100)),
                ('firstname_4', models.CharField(blank=True, max_length=264)),
                ('lastname_4', models.CharField(blank=True, max_length=264)),
                ('Passport_Number_4', models.CharField(blank=True, max_length=200)),
                ('Date_Of_Birth_4', models.CharField(blank=True, max_length=200)),
                ('Sex_4', models.CharField(blank=True, max_length=100)),
                ('firstname_5', models.CharField(blank=True, max_length=264)),
                ('lastname_5', models.CharField(blank=True, max_length=264)),
                ('Passport_Number_5', models.CharField(blank=True, max_length=200)),
                ('Date_Of_Birth_5', models.CharField(blank=True, max_length=200)),
                ('Sex_5', models.CharField(blank=True, max_length=100)),
                ('Organization_Details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Organization_Name', to='generateletter.Organization')),
            ],
        ),
    ]
