# Generated by Django 2.1.7 on 2019-05-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name_plural': 'Manage Organization'},
        ),
        migrations.AlterModelOptions(
            name='visaletters',
            options={'verbose_name_plural': 'Fill Form to Generate Visa Letter'},
        ),
        migrations.AddField(
            model_name='visaletters',
            name='Passport_pic',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
