# Generated by Django 2.1.7 on 2019-05-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateletter', '0002_auto_20190509_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visaletters',
            name='Passport_pic',
        ),
        migrations.AddField(
            model_name='visaletters',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/images'),
        ),
    ]
