# Generated by Django 2.1.7 on 2019-05-09 12:06

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('generateletter', '0005_remove_visaletters_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name_plural': 'Manage Organizations'},
        ),
        migrations.AlterModelOptions(
            name='visaletters',
            options={'verbose_name_plural': 'Fill Form to Generate Visa Letter and Voucher'},
        ),
        migrations.RenameField(
            model_name='visaletters',
            old_name='no_passenger',
            new_name='no_passengers',
        ),
        migrations.AddField(
            model_name='visaletters',
            name='Tourism',
            field=models.CharField(choices=[('TOURISM', 'TOURISM'), ('AIM TOURISM', 'AIM TOURISM')], default='TOURISM', max_length=100),
        ),
        migrations.AddField(
            model_name='visaletters',
            name='multiplicity',
            field=models.CharField(choices=[('single', 'single'), ('double', 'double')], default='SINGLE', max_length=100),
        ),
        migrations.AlterField(
            model_name='visaletters',
            name='Country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='visaletters',
            name='Routes_and_Places',
            field=models.CharField(default='moscow', max_length=500),
        ),
        migrations.AlterField(
            model_name='visaletters',
            name='Sex_1',
            field=models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHER', 'other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='visaletters',
            name='Sex_2',
            field=models.CharField(blank=True, choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHER', 'other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='visaletters',
            name='Sex_3',
            field=models.CharField(blank=True, choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHER', 'other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='visaletters',
            name='Sex_4',
            field=models.CharField(blank=True, choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHER', 'other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='visaletters',
            name='Sex_5',
            field=models.CharField(blank=True, choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHER', 'other')], max_length=100),
        ),
    ]
