# Generated by Django 2.1.7 on 2019-06-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateletter', '0008_auto_20190514_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaletters',
            name='Organization',
            field=models.CharField(blank=True, max_length=264),
        ),
    ]
