# Generated by Django 2.1.7 on 2019-06-11 13:09

from django.db import migrations, models
import generateletter.models


class Migration(migrations.Migration):

    dependencies = [
        ('generateletter', '0010_remove_visaletters_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaletters',
            name='Visa_Letter_Number',
            field=models.IntegerField(default=generateletter.models.Visaletters.number, max_length=264),
        ),
    ]
