# Generated by Django 2.1.7 on 2019-06-11 13:12

from django.db import migrations, models
import generateletter.models


class Migration(migrations.Migration):

    dependencies = [
        ('generateletter', '0011_auto_20190611_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaletters',
            name='Visa_Letter_Number',
            field=models.IntegerField(default=generateletter.models.Visaletters.number),
        ),
    ]
