# Generated by Django 2.1.7 on 2019-06-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateletter', '0012_auto_20190611_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaletters',
            name='Visa_Letter_Number',
            field=models.CharField(max_length=264),
        ),
    ]
