# Generated by Django 2.1.7 on 2019-06-12 02:50

from django.db import migrations, models
import generateletter.models


class Migration(migrations.Migration):

    dependencies = [
        ('generateletter', '0013_auto_20190611_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaletters',
            name='V_Letter_Number',
            field=models.IntegerField(default=generateletter.models.Visaletters.number),
        ),
    ]
