# Generated by Django 2.1.7 on 2019-06-12 08:08

from django.db import migrations, models
import generateletter.models


class Migration(migrations.Migration):

    dependencies = [
        ('generateletter', '0014_visaletters_v_letter_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visaletters',
            name='V_Letter_Number',
        ),
        migrations.AlterField(
            model_name='visaletters',
            name='Visa_Letter_Number',
            field=models.IntegerField(default=generateletter.models.Visaletters.number),
        ),
    ]
