# Generated by Django 2.1.7 on 2019-06-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateletter', '0015_auto_20190612_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaletters',
            name='Visa_Letter_N',
            field=models.CharField(default='<function Visaletters.number at 0x7f7e7be45378>', editable=False, max_length=200),
        ),
    ]
